services:
  mongodb:
    image: zcube/bitnami-compat-mongodb:6.0.5
    environment:
      - MONGODB_USERNAME=okteto
      - MONGODB_PASSWORD=${MONGODB_PASSWORD:-password}
      - MONGODB_DATABASE=okteto
      - MONGODB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD:-password}
      - MONGODB_SYSTEM_LOG_VERBOSITY=0
      - MONGODB_DISABLE_SYSTEM_LOG=no
      - MONGODB_ENABLE_IPV6=no
      - MONGODB_ENABLE_DIRECTORY_PER_DB=no
    ports:
      - 27017
    volumes:
      - data:/bitnami/mongodb

volumes:
  data:
