services:
  mongodb:
    image: mongo:7.0.14
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=okteto   
      - MONGODB_USERNAME=okteto
      - MONGODB_PASSWORD=${MONGODB_PASSWORD:-password}
      
    ports:
      - 27017
    volumes:
      - data:/data/db
      - init.js:/docker-entrypoint-initdb.d/init.js
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  data:
